/**
 * Bindings generated by Wrangler plus user-provided secrets.
 *
 * The Durable Object bindings come from worker-configuration.d.ts. Keeping
 * the secret overlay here avoids hand-writing a second copy of the binding
 * interface while still giving the DO classes type-safe secret access.
 */
export type WorkerEnv = Env & {
	RELAY_KEY?: string
	HBBS_RELAY_URL?: string
	MAX_SESSIONS?: string
	MAX_RELAY_QUEUE_MESSAGES?: string
	MAX_RELAY_QUEUE_BYTES?: string
	MAX_RELAY_BUFFERED_BYTES?: string
	RELAY_HANDSHAKE_TIMEOUT_MS?: string
	MAX_PENDING_CONNECTIONS?: string
	DO_LOCATION_HINT?: string
}
